import { useRef, useId } from 'react';
import { Download, Printer, RotateCcw } from 'lucide-react';

interface CalculatorLayoutProps {
  title: string;
  description: string;
  icon: React.ReactNode;
  accentColor: string;
  children: React.ReactNode;
  onReset: () => void;
}

export default function CalculatorLayout({
  title,
  description,
  icon,
  accentColor,
  children,
  onReset,
}: CalculatorLayoutProps) {
  const resultRef = useRef<HTMLDivElement>(null);

  function handlePrint() {
    window.print();
  }

  function handleDownload() {
    const el = resultRef.current;
    if (!el) return;

    const text = el.innerText;
    const blob = new Blob([`${title}\n${'='.repeat(title.length)}\n\n${text}\n\nGenerated by InvestPredictor`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_').toLowerCase()}_results.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="print-area">
      <div className="mb-6 no-print">
        <div className="flex items-center gap-2 text-xs text-gray-500 mb-2">
          <span>Calculators</span>
          <span>/</span>
          <span className="text-white">{title}</span>
        </div>
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
            style={{ background: `${accentColor}15`, color: accentColor }}
          >
            {icon}
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-white">{title}</h1>
            <p className="text-sm text-gray-500">{description}</p>
          </div>
        </div>
      </div>

      <div ref={resultRef} className="grid lg:grid-cols-5 gap-6">
        {children}
      </div>

      <div className="mt-6 flex items-center gap-3 no-print">
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
        >
          <Download size={14} /> Download Results
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-300 bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
        >
          <Printer size={14} /> Print
        </button>
        <button
          onClick={onReset}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-400 hover:text-white transition-colors ml-auto"
        >
          <RotateCcw size={14} /> Reset
        </button>
      </div>
    </div>
  );
}

// =====================
// Input Field Components
// =====================

interface InputFieldProps {
  label: string;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  prefix?: string;
  suffix?: string;
  type?: 'text' | 'number';
  min?: string;
  max?: string;
  step?: string;
}

export function InputField({
  label,
  value,
  onChange,
  placeholder,
  prefix,
  suffix,
  type = 'number',
  min,
  max,
  step,
}: InputFieldProps) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-400 mb-1.5">{label}</label>
      <div className="relative">
        {prefix && (
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-gray-500 font-medium">
            {prefix}
          </span>
        )}
        <input
          type={type}
          value={value}
          onChange={e => onChange(e.target.value)}
          placeholder={placeholder}
          min={min}
          max={max}
          step={step}
          className={`w-full ${prefix ? 'pl-8' : 'pl-3'} ${suffix ? 'pr-12' : 'pr-3'} py-2.5 text-sm text-white bg-gray-800 border border-gray-700 rounded-lg focus:border-blue-500 focus:outline-none transition-colors placeholder:text-gray-600`}
        />
        {suffix && (
          <span className="absolute right-3 top-1/2 -translate-y-1/2 text-sm text-gray-500 font-medium">
            {suffix}
          </span>
        )}
      </div>
    </div>
  );
}

interface SelectFieldProps {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: { label: string; value: string }[];
}

export function SelectField({ label, value, onChange, options }: SelectFieldProps) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-400 mb-1.5">{label}</label>
      <select
        value={value}
        onChange={e => onChange(e.target.value)}
        className="w-full px-3 py-2.5 text-sm text-white bg-gray-800 border border-gray-700 rounded-lg focus:border-blue-500 focus:outline-none transition-colors"
      >
        {options.map(o => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
    </div>
  );
}

interface SliderFieldProps {
  label: string;
  value: number;
  onChange: (v: number) => void;
  min: number;
  max: number;
  step: number;
  display: string;
}

export function SliderField({ label, value, onChange, min, max, step, display }: SliderFieldProps) {
  return (
    <div>
      <div className="flex items-center justify-between mb-1.5">
        <label className="text-xs font-medium text-gray-400">{label}</label>
        <span className="text-xs font-semibold text-white">{display}</span>
      </div>
      <input
        type="range"
        value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        min={min}
        max={max}
        step={step}
        className="w-full h-1.5 bg-gray-800 rounded-full appearance-none cursor-pointer accent-blue-500"
      />
    </div>
  );
}

// =====================
// Chart Components
// =====================

interface AreaChartProps {
  data: number[];
  labels: string[];
  color?: string;
  height?: number;
  title?: string;
}

export function AreaChart({ data, labels, color = '#3b82f6', height = 200, title }: AreaChartProps) {
  const gradId = useId();
  if (data.length === 0) return null;

  const width = 600;
  const padding = { top: 20, right: 20, bottom: 30, left: 50 };
  const chartW = width - padding.left - padding.right;
  const chartH = height - padding.top - padding.bottom;

  const maxVal = Math.max(...data, 1);
  const minVal = Math.min(...data, 0);
  const range = maxVal - minVal || 1;

  const points = data.map((d, i) => {
    const x = padding.left + (i / Math.max(data.length - 1, 1)) * chartW;
    const y = padding.top + chartH - ((d - minVal) / range) * chartH;
    return { x, y };
  });

  const pathD = points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
  const areaD = `${pathD} L ${points[points.length - 1].x} ${padding.top + chartH} L ${points[0].x} ${padding.top + chartH} Z`;

  // Y-axis labels (4 ticks)
  const yTicks = Array.from({ length: 5 }, (_, i) => minVal + (range * i) / 4);
  // X-axis labels (up to 6)
  const xTickIndices = Array.from({ length: Math.min(6, data.length) }, (_, i) =>
    Math.floor((i * (data.length - 1)) / 5)
  );

  return (
    <div className="w-full">
      {title && <p className="text-xs font-medium text-gray-400 mb-2">{title}</p>}
      <svg viewBox={`0 0 ${width} ${height}`} className="w-full" style={{ height: 'auto' }}>
        <defs>
          <linearGradient id={gradId} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={color} stopOpacity="0.35" />
            <stop offset="100%" stopColor={color} stopOpacity="0.02" />
          </linearGradient>
        </defs>

        {/* Grid lines */}
        {yTicks.map((t, i) => {
          const y = padding.top + chartH - ((t - minVal) / range) * chartH;
          return (
            <g key={i}>
              <line x1={padding.left} y1={y} x2={width - padding.right} y2={y} stroke="#1f2937" strokeWidth="0.5" />
              <text x={padding.left - 8} y={y + 3} textAnchor="end" fill="#6b7280" fontSize="9">
                {formatCompact(t)}
              </text>
            </g>
          );
        })}

        {/* Area + Line */}
        <path d={areaD} fill={`url(#${gradId})`} />
        <path d={pathD} fill="none" stroke={color} strokeWidth="2" strokeLinejoin="round" />

        {/* X-axis labels */}
        {xTickIndices.map((idx, i) => {
          const p = points[idx];
          return (
            <text key={i} x={p.x} y={height - 8} textAnchor="middle" fill="#6b7280" fontSize="9">
              {labels[idx]}
            </text>
          );
        })}
      </svg>
    </div>
  );
}

interface DonutChartProps {
  segments: { label: string; value: number; color: string }[];
  centerLabel?: string;
  centerValue?: string;
  size?: number;
}

export function DonutChart({ segments, centerLabel, centerValue, size = 180 }: DonutChartProps) {
  const total = segments.reduce((sum, s) => sum + s.value, 0);
  if (total === 0) return null;

  const radius = size / 2 - 20;
  const innerRadius = radius * 0.62;
  const cx = size / 2;
  const cy = size / 2;

  let currentAngle = -Math.PI / 2;

  const arcs = segments.map(s => {
    const angle = (s.value / total) * Math.PI * 2;
    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    currentAngle = endAngle;

    const x1 = cx + radius * Math.cos(startAngle);
    const y1 = cy + radius * Math.sin(startAngle);
    const x2 = cx + radius * Math.cos(endAngle);
    const y2 = cy + radius * Math.sin(endAngle);
    const x3 = cx + innerRadius * Math.cos(endAngle);
    const y3 = cy + innerRadius * Math.sin(endAngle);
    const x4 = cx + innerRadius * Math.cos(startAngle);
    const y4 = cy + innerRadius * Math.sin(startAngle);

    const largeArc = angle > Math.PI ? 1 : 0;

    return {
      ...s,
      path: `M ${x1} ${y1} A ${radius} ${radius} 0 ${largeArc} 1 ${x2} ${y2} L ${x3} ${y3} A ${innerRadius} ${innerRadius} 0 ${largeArc} 0 ${x4} ${y4} Z`,
      pct: (s.value / total) * 100,
    };
  });

  return (
    <div className="flex flex-col items-center gap-4">
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        {arcs.map((a, i) => (
          <path key={i} d={a.path} fill={a.color} />
        ))}
        {centerValue && (
          <text x={cx} y={cy - 2} textAnchor="middle" fill="#fff" fontSize="14" fontWeight="700">
            {centerValue}
          </text>
        )}
        {centerLabel && (
          <text x={cx} y={cy + 14} textAnchor="middle" fill="#9ca3af" fontSize="9">
            {centerLabel}
          </text>
        )}
      </svg>
      <div className="space-y-2 w-full">
        {arcs.map((a, i) => (
          <div key={i} className="flex items-center justify-between text-xs">
            <div className="flex items-center gap-2">
              <div className="w-2.5 h-2.5 rounded-sm" style={{ background: a.color }} />
              <span className="text-gray-400">{a.label}</span>
            </div>
            <span className="text-white font-semibold">{formatCurrency(a.value)} ({a.pct.toFixed(1)}%)</span>
          </div>
        ))}
      </div>
    </div>
  );
}

interface BarChartProps {
  data: { label: string; value: number; color?: string }[];
  height?: number;
  title?: string;
  defaultColor?: string;
}

export function BarChart({ data, height = 200, title, defaultColor = '#3b82f6' }: BarChartProps) {
  if (data.length === 0) return null;
  const maxVal = Math.max(...data.map(d => Math.abs(d.value)), 1);

  return (
    <div className="w-full">
      {title && <p className="text-xs font-medium text-gray-400 mb-2">{title}</p>}
      <div className="flex items-end gap-1.5" style={{ height }}>
        {data.map((d, i) => {
          const h = (Math.abs(d.value) / maxVal) * (height - 30);
          return (
            <div key={i} className="flex-1 flex flex-col items-center gap-1 group">
              <span className="text-[9px] text-gray-500 opacity-0 group-hover:opacity-100 transition-opacity">
                {formatCompact(d.value)}
              </span>
              <div
                className="w-full rounded-t transition-all hover:opacity-80"
                style={{
                  height: `${Math.max(h, 2)}px`,
                  background: d.color ?? defaultColor,
                }}
              />
              <span className="text-[9px] text-gray-500 text-center truncate w-full">{d.label}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// =====================
// Result Card
// =====================

interface ResultCardProps {
  label: string;
  value: string;
  sublabel?: string;
  accent?: boolean;
  color?: string;
}

export function ResultCard({ label, value, sublabel, accent, color }: ResultCardProps) {
  return (
    <div
      className={`p-4 rounded-xl border ${
        accent
          ? 'bg-blue-500/10 border-blue-500/30'
          : 'bg-gray-800/50 border-gray-700'
      }`}
      style={accent && color ? { background: `${color}10`, borderColor: `${color}40` } : undefined}
    >
      <p className="text-xs text-gray-500 mb-1">{label}</p>
      <p className="text-lg font-bold text-white">{value}</p>
      {sublabel && <p className="text-xs text-gray-500 mt-0.5">{sublabel}</p>}
    </div>
  );
}

// =====================
// Formatting Utilities
// =====================

export function formatCurrency(value: number): string {
  if (Math.abs(value) >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (Math.abs(value) >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  if (Math.abs(value) >= 1e3) return `$${(value / 1e3).toFixed(1)}K`;
  return `$${value.toFixed(0)}`;
}

export function formatFullCurrency(value: number): string {
  return `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatCompact(value: number): string {
  if (Math.abs(value) >= 1e9) return `${(value / 1e9).toFixed(1)}B`;
  if (Math.abs(value) >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (Math.abs(value) >= 1e3) return `${(value / 1e3).toFixed(1)}K`;
  return value.toFixed(0);
}
